version: '3.8'

services:
  app:
    container_name: cx-v2
    image: cx-v2
    build:
      context: .
      args:
        - FIREBASE_API_KEY=${FIREBASE_API_KEY}
        - MAPS_API_KEY=${MAPS_API_KEY}
        - FIREBASE_API_DOMAIN=${FIREBASE_API_DOMAIN}
        - VERSION=${VERSION}
        - HASURA_WS=${HASURA_WS}
        - HASURA_HTTP=${HASURA_HTTP}
        - APP_ENV=${APP_ENV}
        - GROWTHBOOK_API_HOST=${GROWTHBOOK_API_HOST}
        - GROWTHBOOK_CLIENT_KEY=${GROWTHBOOK_CLIENT_KEY}
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
        - SENTRY_RELEASE=${VERSION}
        - SENTRY_ORG=talview
        - CREATED_AT=${CREATED_AT}
        - LOKALISE_TOKEN=${LOKALISE_TOKEN}
        - LOKALISE_PROJECT_ID=${LOKALISE_PROJECT_ID}
        - ESLINT_USE_FLAT_CONFIG=${ESLINT_USE_FLAT_CONFIG}
        - CHROMATIC_PROJECT_TOKEN=${CHROMATIC_PROJECT_TOKEN}
        - CODECOV_TOKEN=${CODECOV_TOKEN}
        - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
        - OLD_CANDIDATE_X_URL=${OLD_CANDIDATE_X_URL}
        - PADDLE_CLIENT_TOKEN=${PADDLE_CLIENT_TOKEN}
    ports:
      - 2100:80
