/* eslint-disable @typescript-eslint/no-require-imports */
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const webpackMerge = require('webpack-merge');
const common = require('./webpack.common');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
// const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');

require('webpack-dev-server');

module.exports = webpackMerge.merge(common, {
  mode: 'development',
  devtool: 'inline-source-map',

  devServer: {
    port: 2100,
    historyApiFallback: true,
  },
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      // maxInitialRequests: 5, // Limit initial chunks to speed up load time
      // minSize: 50000, // Minimum size for a chunk to be created i.e. 50KB
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors-bundle',
          chunks: 'all',
        },
      },
    },
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'public/index.html',
      favicon: 'public/assets/images/favicon.ico',
    }),

    new webpack.EnvironmentPlugin({
      NODE_ENV: 'development',
    }),

    new ReactRefreshWebpackPlugin(),

    // new BundleAnalyzerPlugin({
    //   // analyzerMode: 'server', // http://localhost:7777
    //   // statsFilename: 'bundleStats.json',
    //   analyzerMode: 'static',
    //   reportFilename: 'bundle-report.html',
    //   analyzerPort: 7777,
    //   openAnalyzer: false,
    //   generateStatsFile: true, // Generate a stats file (useful for CI/CD)
    // }),
  ],
});
